
# This file is used by Supabase CLI to manage your project configuration.
# Learn more: https://supabase.com/docs/reference/cli/config

[project]
name = "motojojo-events"

[api]
enabled = true
port = 54323
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54321
api_url = "http://127.0.0.1:54321"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[realtime]
enabled = true

[analytics]
enabled = false
port = 54324
vector_port = 54325

